[package]
name = "verify-image-signatures"
version = "0.1.1"
authors = ["raulcabello <raul.cabello@suse.com>","viccuad <vcuadradojuan@suse.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
k8s-openapi = { version = "0.11.0", default_features = false, features = ["v1_20"] }
kubewarden-policy-sdk = { git = "https://github.com/kubewarden/policy-sdk-rust", tag = "v0.4.0" }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2.7"
wapc-guest = "0.4.0"
wildmatch = "2.1.0"

[dev-dependencies]
rstest = "0.12.0"
serial_test = "0.6.0"
mockall = "0.11.0"
anyhow = "1.0.56"
