# No need to set modifyImagesWithDigest to `true` - this is the default
# behavior
signatures:
  - image: "ghcr.io/kubewarden/tests/pod-privileged:v0.2.1"
    certificates:
    # user-1
    - |
      -----BEGIN CERTIFICATE-----
      MIICsjCCAligAwIBAgIUZfoeZRPm91CZevZ1fPbn4+KRd0owCgYIKoZIzj0EAwIw
      gZIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
      bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xIzAhBgNVBAsTGkt1YmV3YXJkZW4g
      SW50ZXJtZWRpYXRlIENBMSMwIQYDVQQDExpLdWJld2FyZGVuIEludGVybWVkaWF0
      ZSBDQTAeFw0yMjExMjkxNjMzMDBaFw0yMzExMjkxNjMzMDBaMIGFMQswCQYDVQQG
      EwJERTEQMA4GA1UECBMHQmF2YXJpYTESMBAGA1UEBxMJTnVyZW1iZXJnMRMwEQYD
      VQQKEwpLdWJld2FyZGVuMRgwFgYDVQQLEw9LdWJld2FyZGVuIFVzZXIxITAfBgNV
      BAMTGHVzZXIxLmN1c3RvbS13aWRnZXRzLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
      AwEHA0IABMcH06eiQcY+sGvNfs+FBxhiv6+4vYIwvCTOVcJTxQpGO2kHo9nkIHGm
      ew6G0ZMsKuyheJvCd1LUJHz+RSyDMmOjgZYwgZMwDgYDVR0PAQH/BAQDAgeAMBMG
      A1UdJQQMMAoGCCsGAQUFBwMDMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFKPNku64
      U0oZNvqknxVxuLawHDoLMB8GA1UdIwQYMBaAFKl15W6Co/ODIBgv1K2RB+xP2CN8
      MB4GA1UdEQQXMBWBE3VzZXIxQGt1YmV3YXJkZW4uaW8wCgYIKoZIzj0EAwIDSAAw
      RQIhANxvHFVCzQ7BBDTzY380U9nGqw5ZMpxsKA676Kihdyk6AiB4AmeNpCW+QSry
      xbm4q79liMgu9eUfkeB8IpstcbXtkg==
      -----END CERTIFICATE-----
    # user-2
    - |
      -----BEGIN CERTIFICATE-----
      MIICsTCCAligAwIBAgIUNBuovE9BVN1GvXXLgu17GZu1+ZowCgYIKoZIzj0EAwIw
      gZIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
      bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xIzAhBgNVBAsTGkt1YmV3YXJkZW4g
      SW50ZXJtZWRpYXRlIENBMSMwIQYDVQQDExpLdWJld2FyZGVuIEludGVybWVkaWF0
      ZSBDQTAeFw0yMjEyMDIwODMxMDBaFw0yMzEyMDIwODMxMDBaMIGFMQswCQYDVQQG
      EwJERTEQMA4GA1UECBMHQmF2YXJpYTESMBAGA1UEBxMJTnVyZW1iZXJnMRMwEQYD
      VQQKEwpLdWJld2FyZGVuMRgwFgYDVQQLEw9LdWJld2FyZGVuIFVzZXIxITAfBgNV
      BAMTGHVzZXIyLmN1c3RvbS13aWRnZXRzLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
      AwEHA0IABBabfXpRGxJabHT6jR38wkfS1DKq7LKHF0hEwX4MyVzCAtBQxdn4/tFa
      u01JPc4z7+V7Ge475s8phzgIvV/s/PCjgZYwgZMwDgYDVR0PAQH/BAQDAgeAMBMG
      A1UdJQQMMAoGCCsGAQUFBwMDMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFP25XwId
      pSmu0476QlqoW2RQadYEMB8GA1UdIwQYMBaAFKl15W6Co/ODIBgv1K2RB+xP2CN8
      MB4GA1UdEQQXMBWBE3VzZXIyQGt1YmV3YXJkZW4uaW8wCgYIKoZIzj0EAwIDRwAw
      RAIgQ6dM+qqKa8rjxunxi9i0Lcn48uvx0lbx0wyUNL5eykYCICffSe/zE/oLO6yK
      HvAlQzB9BZygnEacwWSGNERsAjYp
      -----END CERTIFICATE-----
    certificateChain:
    - |
      -----BEGIN CERTIFICATE-----
      MIIClDCCAjmgAwIBAgIUeiQHILF0NXVHkb+CTk5Ja8781YswCgYIKoZIzj0EAwIw
      gYIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
      bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xGzAZBgNVBAsTEkt1YmV3YXJkZW4g
      Um9vdCBDQTEbMBkGA1UEAxMSS3ViZXdhcmRlbiBSb290IENBMB4XDTIyMTEwOTE1
      MzMwMFoXDTIzMTEwOTE1MzMwMFowgZIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdC
      YXZhcmlhMRIwEAYDVQQHEwlOdXJlbWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4x
      IzAhBgNVBAsTGkt1YmV3YXJkZW4gSW50ZXJtZWRpYXRlIENBMSMwIQYDVQQDExpL
      dWJld2FyZGVuIEludGVybWVkaWF0ZSBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEH
      A0IABJZW2kFEbqARRaodcn+Qq868EHRLEkUAOGh43p+I8fXhAuMBfJnUsPiP8BaN
      mVcwM6xfhb0GQJIWOZI1yf20klijezB5MA4GA1UdDwEB/wQEAwIBBjATBgNVHSUE
      DDAKBggrBgEFBQcDAzASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBTcZARm
      g8MupZs7mneH/Ct47WjNGzAfBgNVHSMEGDAWgBRA0I1bmD1zfHOEB1IFkQb7fUKl
      SzAKBggqhkjOPQQDAgNJADBGAiEAxLREbJPA+3pT/pWuJMdrhk43Ef2+I08O+EgN
      JqPeI9QCIQDratUrVqbMVaqO4V5caAt0W5DKGZ6jHEOqTSIJc4Y+9Q==
      -----END CERTIFICATE-----
    - |
      -----BEGIN CERTIFICATE-----
      MIICSTCCAfCgAwIBAgIUGmnXEKIgtO6jSvoFkeQtrnByp/4wCgYIKoZIzj0EAwIw
      gYIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
      bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xGzAZBgNVBAsTEkt1YmV3YXJkZW4g
      Um9vdCBDQTEbMBkGA1UEAxMSS3ViZXdhcmRlbiBSb290IENBMB4XDTIyMTEwOTE1
      MzMwMFoXDTI3MTEwODE1MzMwMFowgYIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdC
      YXZhcmlhMRIwEAYDVQQHEwlOdXJlbWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4x
      GzAZBgNVBAsTEkt1YmV3YXJkZW4gUm9vdCBDQTEbMBkGA1UEAxMSS3ViZXdhcmRl
      biBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHJ3TupfOSIGErxvL
      dCamlcXPXnZZJq01rWYZSH6M7JfZWxK8d/U26gojkI8UlkJJzrHkeyzU5Cx6gkkU
      HcnGOKNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
      BBYEFEDQjVuYPXN8c4QHUgWRBvt9QqVLMAoGCCqGSM49BAMCA0cAMEQCIDgojTBu
      mCndMqbm4ssXAuOxVFQky7eDbh72dTKveTijAiAKQqe/hgw6Of8pyRNahqyKu/vH
      U3RFLVLN8f8LGQyn/A==
      -----END CERTIFICATE-----
    requireRekorBundle: false
